### PR TITLE
Add Sampa autogenerated reading group calendar for distributed algorithms group

### PR DESCRIPTION
**Pull request by bholt**
This adds stuff to do the automagical schedule-generating reading group webpage stuff the Sampa group uses for our reading groups. It's pretty awesome, you just edit the yaml schedule in the frontmatter and it generates the html table and calendar, which you can subscribe to so you'll have the links to the papers and who's presenting and where, all in your own personal calendar!

@wilcoxjay what do you think of using this for the distributed algorithms reading group this summer? @jamesbornholt helped me confirm that this works with the vanilla github pages deployment.

### CODE REVIEW

**Comment by bholt** [comment]
You can see what it looks like here: http://bholt.github.io/courses/su15/underground-distributed/

**Comment by dwoos** [comment]
:+1: @wilcoxjay i vote to merge and use for the other reading groups as well

**Comment by wilcoxjay** [comment]
Looks cool. I will fixup and merge later tonight.

**Comment by wilcoxjay** [comment]
I have implemented this.

**Pull request closed without merging**
